pipeline{
   agent{
    docker{
        image 'maven:3.8.7-openjdk-18-slim'
        args '-v /var/jenkins_home/:/root/.m2' 
    }
   }

   stages{

    stage('checkout'){
      steps{  
       sh 'echo checkedout'
       // git branch: 'main', url: 'https://github.com/Vigneshbalajiee/My_DevOPS.git'
      }  
    }

    stage('build the package'){
       steps{ 
        //build the war file
        sh 'cd Projects/Project3 - complete CICD/addressbook-app && mvn clean package'
       }
    }

    stage('build and push image to hub'){
        environment{
            IMAGE = "vigneshbalajiee/addressbook:${BUILD_NUMBER}"
            CRED = credentials('Docker')
        }
        steps{
            script{
                sh 'cd Projects/Project3 - complete CICD/addressbook-app && docker build -t ${IMAGE} .'
                def dockerImage = docker.image("${IMAGE}")
                docker.withRegistry('https://index.docker.io/v1/', "CRED"){
                    dockerImage.push()
                    dockerImage.pull()
                    dockerImage.run('-d')
                }
            }
        }
    }

    stage('update and push deplyment to git') {
        
        environment{
            USER = "Vigneshbalajiee"
            REPO = "My_DevOPS"
        }
        steps{    
            withCredentials([string(credentialsID: 'github', variable: 'GITHUB_TOKEN')]){
                sh '''
                  git config user.name "Vigneshbalajiee"
                  BUILD_NUMBER = ${BUILD_NUMBER}
                  sed -i "s/xxx/${BUILD_NUMBER}/g" Projects/Project3 - complete CICD/addressbook_manifest/deployment.yml
                  git add Projects/Project3 - complete CICD/addressbook_manifest/deployment.yml
                  git commit -m "updated yml with ${BUILD_NUMBER}"
                  git push https://${GITHUB_TOKEN}@github.com/${USER}/${REPO} HEAD:main
            '''
            }

        }
    }

   }
}