pipeline{
   agent{
    docker{
        image 'maven:3.8.1-jdk-11'
        args '--user root -v /var/jenkins_home/:/root/.m2 -v /var/run/docker.sock:/var/run/docker.sock' 
    }
   }

   stages{

    stage('checkout'){
      steps{  
       sh 'echo checkedout'
       // git branch: 'main', url: 'https://github.com/Vigneshbalajiee/My_DevOPS.git'
      }  
    }

    stage('build the package'){
       steps{ 
        //build the war file
        sh 'ls -ltr'
        sh 'cd "Projects/Project3 - complete CICD/addressbook-app" && mvn clean install -DskipTests'
       }
    }
    stage('Install Docker') {
            steps {
                script {
                    sh '''
                    apt-get update
                    apt-get install -y docker.io
                    docker --version
                    '''
                }
            }
        }

    stage('build and push image to hub'){
        environment{
            IMAGE = "vigneshbalajiee/addressbook:${BUILD_NUMBER}"
            CRED = credentials('Docker')
        }
        steps{
            script{
                sh 'docker --version'
                sh 'cd "Projects/Project3 - complete CICD/addressbook-app" && docker build -t ${IMAGE} .'
                def dockerImage = docker.image("${IMAGE}")
                docker.withRegistry('https://index.docker.io/v1/', 'Docker'){
                    dockerImage.push()
               
                }
            }
        }
    }

    stage('update and push deployment to git') {
        environment {
            USER = "Vigneshbalajiee"

            REPO = "My_DevOPS"
        }
        steps {
            withCredentials([string(credentialsId: 'github', variable: 'GITHUB_TOKEN')]) {
                script {
                    sh '''
                        git config user.name "Vigneshbalajiee"
                        git config user.email "vigneshbalajiee15@gmail.com"
                        BUILD_NUMBER=${BUILD_NUMBER}
                       
                        sed -i "s|image: vigneshbalajiee/addressbook:.*|image: vigneshbalajiee/addressbook:${BUILD_NUMBER}|g" "Projects/Project3 - complete CICD/addressbook_manifest/deployment.yml"
                        git add "Projects/Project3 - complete CICD/addressbook_manifest/deployment.yml"
                        git commit -m "updated yml with ${BUILD_NUMBER}"
                        git push https://${GITHUB_TOKEN}@github.com/${USER}/${REPO} HEAD:main
                    '''
                }
            }
        }
    }
   }
}
